-- Supprimer les contraintes de clés étrangères
ALTER TABLE profils DROP CONSTRAINT IF EXISTS profils_id_diplome_fkey;
ALTER TABLE questions DROP CONSTRAINT IF EXISTS questions_id_profil_fkey;
ALTER TABLE reponses_question DROP CONSTRAINT IF EXISTS reponses_question_id_question_fkey;
ALTER TABLE candidats DROP CONSTRAINT IF EXISTS candidats_id_personne_fkey;
ALTER TABLE candidats DROP CONSTRAINT IF EXISTS candidats_id_annonce_fkey;
ALTER TABLE tests DROP CONSTRAINT IF EXISTS tests_id_candidat_fkey;
ALTER TABLE planning_entretien DROP CONSTRAINT IF EXISTS planning_entretien_id_candidat_fkey;
ALTER TABLE planning_entretien DROP CONSTRAINT IF EXISTS planning_entretien_etat_fkey;
ALTER TABLE planning_entretien DROP CONSTRAINT IF EXISTS planning_entretien_id_appreciation_fkey;
ALTER TABLE planning_entretien DROP CONSTRAINT IF EXISTS planning_entretien_id_responsable_fkey;
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_id_personne_fkey;
ALTER TABLE contrats DROP CONSTRAINT IF EXISTS contrats_id_candidat_fkey;
ALTER TABLE essais DROP CONSTRAINT IF EXISTS essais_id_personne_fkey;
ALTER TABLE essais DROP CONSTRAINT IF EXISTS essais_id_contrat_fkey;
ALTER TABLE essais DROP CONSTRAINT IF EXISTS essais_id_etat_fkey;
ALTER TABLE employes DROP CONSTRAINT IF EXISTS employes_id_personne_fkey;
ALTER TABLE employes DROP CONSTRAINT IF EXISTS employes_id_contrat_fkey;
ALTER TABLE employes DROP CONSTRAINT IF EXISTS employes_id_departement_fkey;
ALTER TABLE historique_validation DROP CONSTRAINT IF EXISTS historique_validation_id_employe_fkey;
ALTER TABLE historique_validation DROP CONSTRAINT IF EXISTS historique_validation_id_candidat_fkey;
ALTER TABLE responsable_entretien DROP CONSTRAINT IF EXISTS responsable_entretien_id_employe_fkey;
ALTER TABLE responsable_entretien DROP CONSTRAINT IF EXISTS responsable_entretien_id_profil_fkey;
ALTER TABLE config_entretien DROP CONSTRAINT IF EXISTS config_entretien_id_departement_fkey;
ALTER TABLE disponibilite_entretien DROP CONSTRAINT IF EXISTS disponibilite_entretien_id_responsable_fkey;

-- Supprimer les vues
DROP VIEW IF EXISTS view_scoring;

-- Supprimer toutes les tables (dans l’ordre des dépendances)
DROP TABLE IF EXISTS disponibilite_entretien;
DROP TABLE IF EXISTS responsable_entretien;
DROP TABLE IF EXISTS historique_validation;
DROP TABLE IF EXISTS employes;
DROP TABLE IF EXISTS essais;
DROP TABLE IF EXISTS contrats;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS message_automatique;
DROP TABLE IF EXISTS planning_entretien;
DROP TABLE IF EXISTS appreciation;
DROP TABLE IF EXISTS etat;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS candidats;
DROP TABLE IF EXISTS reponses_question;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS personnes;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS profils;
DROP TABLE IF EXISTS type_contrats;
DROP VIEW IF EXISTS v_candidats_personnes CASCADE;
DROP VIEW IF EXISTS v_responsable_personnes CASCADE;
DROP VIEW IF EXISTS v_disponibilite_employe_valide CASCADE;
DROP VIEW IF EXISTS v_entretien_candidat_apres_une_date CASCADE;
DROP VIEW IF EXISTS v_responsable_avec_departement CASCADE;
DROP VIEW IF EXISTS v_planning_entretien_recent_responsable CASCADE;
DROP TABLE IF EXISTS departements;
DROP TABLE IF EXISTS filieres;
DROP TABLE IF EXISTS diplomes;
DROP TABLE IF EXISTS annonces;
DROP TABLE IF EXISTS utilisateurs;
DROP TABLE IF EXISTS jour_ferie;
DROP TABLE IF EXISTS config_entretien;
