-- Se connecter à la base
\c aufildespages

------------------- DROP VUES -----------------
DROP VIEW IF EXISTS view_scoring CASCADE;

-- ----------------- DROP TABLES -----------------
DROP TABLE IF EXISTS historique_validation CASCADE;
DROP TABLE IF EXISTS disponibilite_employe CASCADE;
DROP TABLE IF EXISTS employes CASCADE;
DROP TABLE IF EXISTS essais CASCADE;
DROP TABLE IF EXISTS contrats CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS planning_entretien CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS candidats CASCADE;
DROP TABLE IF EXISTS reponses_question CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS profils CASCADE;
DROP TABLE IF EXISTS utilisateurs CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS personnes CASCADE;
DROP TABLE IF EXISTS annonces CASCADE;
DROP TABLE IF EXISTS diplomes CASCADE;
DROP TABLE IF EXISTS filieres CASCADE;
DROP TABLE IF EXISTS departements CASCADE;
DROP TABLE IF EXISTS etat CASCADE;
DROP TABLE IF EXISTS appreciation CASCADE;
DROP TABLE IF EXISTS message_automatique CASCADE;
DROP TABLE IF EXISTS type_contrats CASCADE;
