CREATE TABLE personnes (
  id_personne INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar,
  prenom varchar,
  date_naissance date,
  contact varchar UNIQUE,
  lien_image varchar
);

-- 1	"Randria"	"Mickael"	"1998-05-21"	"0341234567"	"img/PHOTO_CV/Capture-d-Aoy-cran-du-2025-09-13-21-03-11_1758134870.png"
-- 2	"Rakoto"	"Sonia"	"2000-11-02"	"0347654321"	"img/PHOTO_CV/Capture-d-Aoy-cran-du-2025-08-20-10-36-45_1758135778.png"

CREATE TABLE annonces (
  id_annonce INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre varchar,
  lien text,
  date_publication date,
  date_expiration date,
  nombre_poste int
);

-- INSERT INTO annonces (titre, lien, date_publication, date_expiration, nombre_poste) VALUES
-- ('Développeur Web Junior', 'https://exemple.com/annonces/dev-web-junior', '2025-09-01', '2025-09-30', 2),
-- ('Assistant Comptable', 'https://exemple.com/annonces/assistant-comptable', '2025-09-05', '2025-10-05', 1),
-- ('Designer Graphique', 'https://exemple.com/annonces/designer-graphique', '2025-09-10', '2025-09-25', 3),
-- ('Chargé de Communication', 'https://exemple.com/annonces/charge-communication', '2025-08-20', '2025-09-20', 1),
-- ('Ingénieur Systèmes et Réseaux', 'https://exemple.com/annonces/ingenieur-systemes', '2025-09-15', '2025-10-15', 2);

CREATE TABLE candidats (
  id_candidat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_personne int,
  id_annonce int,
  poste varchar
);

CREATE TABLE departements (
  id_departement INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar
);

CREATE TABLE diplomes (
  id_diplome INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom varchar,
  niveau varchar
);

CREATE TABLE contrats (
  id_contrat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat int,
  type_contrat varchar,
  url_contrat varchar
);

CREATE TABLE profils (
  id_profil INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre varchar,
  id_departement int,
  competences text,
  skills text,
  loisirs text,
  niveau_etudes varchar(100),
  id_diplome int,
  experience_pro text,
  certifications text,
  langues text,
  lien_suggestion_annonce varchar ,
  id_type_contract int ,
  est_minimum BOOLEAN DEFAULT FALSE
);
