\c jemima

DROP DATABASE IF EXISTS aufildespages;
CREATE DATABASE aufildespages;

\c aufildespages

-- ================== TABLES ==================
CREATE TABLE annonces (
  id_annonce INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profil INT,
  titre VARCHAR,
  date_publication DATE,
  date_expiration DATE,
  nombre_poste INT, 
  lien TEXT
);

CREATE TABLE diplomes (
  id_diplome INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR,
  niveau INT
);


    CREATE TABLE treshold(
      id_treshold INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      valeur DECIMAL(5,2),
      date_treshold TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO treshold (valeur) VALUES (0.20);

  -- 

CREATE TABLE departements(
  id_departement INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR
);

CREATE TABLE filieres (
  id_filiere INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR
);

CREATE TABLE type_contrats(
  id_type_contrat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR
);


CREATE TABLE profils (
  id_profil INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre VARCHAR,
  competences TEXT,
  skills TEXT,
  loisirs TEXT,
  id_diplome INT,
  id_filiere INT,
  experience_pro TEXT,
  certifications TEXT,
  langues TEXT,
  id_type_contrat INT,
  id_departement INT,
  est_minimum BOOLEAN DEFAULT FALSE
);

CREATE TABLE utilisateurs(
  id_utilisateur SERIAL PRIMARY KEY,
  nom VARCHAR(255) UNIQUE NOT NULL,
  mdp VARCHAR(255) NOT NULL,
  date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_sortie TIMESTAMP
);


CREATE TABLE admins (
  id_admin SERIAL PRIMARY KEY,
  id_employe INT,
  nom VARCHAR(255) UNIQUE NOT NULL,
  mdp VARCHAR(255) NOT NULL,
  date_affiliation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_fin_affiliation TIMESTAMP
);

CREATE TABLE personnes (
  id_personne INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR,
  prenom VARCHAR,
  date_naissance DATE,
  contact VARCHAR ,
  lien_image VARCHAR
);

CREATE TABLE api(
  id_api INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR,
  cle_api VARCHAR
);

CREATE TABLE questions (
  id_question INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT,
  id_profil INT,
  note DECIMAL(5,2)
);

CREATE TABLE reponses_question (
  id_reponse INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_question INT,
  reponse TEXT,
  est_correct BOOLEAN
);

CREATE TABLE candidats (
  id_candidat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_personne INT,
  id_annonce INT,
  id_profil INT,
  cv_url VARCHAR,
  poste VARCHAR ,
  id_utilisateur INT
);

CREATE TABLE tests (
  id_test INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat INT,
  id_annonce INT,
  score_test DECIMAL(5,2),
  date_test DATE
);

CREATE TABLE etat (
  id_etat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR
);

CREATE TABLE appreciation (
  id_appreciation INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_appreciation TEXT,
  code INT
);


CREATE TABLE planning_entretien (
  id_entretien INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat int,
  id_responsable int,
  date_heure_entretien timestamp,
  score_entretien decimal(5,2),
  etat int,
  id_appreciation int
);

CREATE TABLE message_automatique (
  id_message_automatique INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT
);

CREATE TABLE notifications (
  id_notification INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_personne INT,
  message TEXT,
  date_notification TIMESTAMP
);

CREATE TABLE contrats (
  id_contrat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat INT,
  id_type_contrat INT,
  url_contrat VARCHAR
);

CREATE TABLE essais (
  id_essai INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_personne INT,
  id_contrat INT,
  id_etat INT,
  date_debut DATE,
  date_fin DATE
);

CREATE TABLE employes (
  id_employe INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_personne INT,
  id_contrat INT,
  id_departement INT,
  poste VARCHAR,
  date_embauche DATE
);

CREATE TABLE disponibilite_employe (
  id_dispo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_employe INT,
  heure_debut TIME,
  heure_fin TIME
);

CREATE TABLE historique_validation (
  id_historique_validation INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_employe INT,
  id_candidat INT,
  date_heure_validation TIMESTAMP,
  id_etat int
);



CREATE TABLE profilsCV (
  id_profil INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre VARCHAR,
  competences TEXT,
  skills TEXT,
  loisirs TEXT,
  id_diplome INT REFERENCES diplomes(id_diplome),
  filiere TEXT,
  experience_pro TEXT,
  certifications TEXT,
  langues TEXT,
  id_type_contrat INT,
  est_minimum BOOLEAN DEFAULT FALSE,
  id_departement INT REFERENCES departements(id_departement)
);

CREATE TABLE cv_candidats(
  id_cv_candidats INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat INT REFERENCES candidats(id_candidat), 
  competences TEXT,
  skills TEXT,
  loisirs TEXT,
  id_diplome INT REFERENCES diplomes(id_diplome),
  filiere TEXT,
  experience_pro TEXT,
  certifications TEXT,
  langues TEXT,
  date_deposition TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);  

CREATE TABLE status_validation_cv(
  id_status_validation_cv INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statut VARCHAR
);

INSERT INTO status_validation_cv (statut) VALUES('Validé'),('Rejeté');

CREATE TABLE validation_cv(
  id_validation_cv INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_candidat INT REFERENCES candidats(id_candidat),
  id_cv_candidat INT REFERENCES cv_candidats(id_cv_candidats),
  id_status_validation_cv INT REFERENCES status_validation_cv(id_status_validation_cv),
  similarite DECIMAL(5,2)

);



-- ================== VUES ==================


--TABLE QUI PERMET DE SAVOIR QUI SONT LES RESPONSABLES DES ENTRETIENS 
CREATE TABLE responsable_entretien(
  id_responsable int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_profil INT,
  id_employe INT,
  ordre_passage INT
);

CREATE TABLE disponibilite_entretien (
  id_dispo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_responsable INT,
  heure_debut TIME, 
  heure_fin TIME,
  jour INT,
  est_valide BOOLEAN DEFAULT TRUE
);
CREATE TABLE jour_ferie(
  id_jour_ferie   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE
);
CREATE TABLE config_entretien(
  id_config_entretien int GENERATED BY DEFAULT AS IDENTITY,
  id_departement int,
  duree_entretien INTERVAL
);

CREATE VIEW view_scoring AS
SELECT 
    c.id_candidat,
    t.score_test,
    pe.score_entretien,
    ROUND(((COALESCE(t.score_test,0) + COALESCE(pe.score_entretien,0)) / 
           (CASE WHEN (t.score_test IS NOT NULL)::int + (pe.score_entretien IS NOT NULL)::int > 0 
                 THEN (t.score_test IS NOT NULL)::int + (pe.score_entretien IS NOT NULL)::int 
                 ELSE 1 END)
    )::numeric, 2) AS moyenne
FROM candidats c
LEFT JOIN tests t ON c.id_candidat = t.id_candidat
LEFT JOIN planning_entretien pe ON c.id_candidat = pe.id_candidat;




create or replace view historique_contrat as 
SELECT c.id_contrat,
       c.url_contrat,
       cand.id_candidat,
       cand.poste,
       tc.nom AS type_contrat,
       e.nom AS etat,
       hv.date_heure_validation,
       pv.nom || ' ' || pv.prenom AS redacteur,
       pc.nom || ' ' || pc.prenom AS candidat
FROM contrats c
JOIN candidats cand ON c.id_candidat = cand.id_candidat
JOIN type_contrats tc ON c.id_type_contrat = tc.id_type_contrat
LEFT JOIN (
    SELECT DISTINCT ON (id_candidat) *
    FROM historique_validation
    ORDER BY id_candidat, date_heure_validation DESC
) hv ON hv.id_candidat = cand.id_candidat
LEFT JOIN etat e ON hv.id_etat = e.id_etat
LEFT JOIN employes emp ON hv.id_employe = emp.id_employe
LEFT JOIN personnes pv ON emp.id_personne = pv.id_personne   -- validateur
LEFT JOIN personnes pc ON cand.id_personne = pc.id_personne -- candidat
ORDER BY e.nom, hv.date_heure_validation DESC;

--recuperer les candidats avec leurs informatiions 
CREATE OR REPLACE VIEW v_candidats_personnes AS
SELECT per.*,
        ca.id_candidat,
        ca.id_annonce,
        ca.id_profil,
        ca.cv_url,
        ca.poste
FROM  candidats ca 
JOIN personnes per
on ca.id_personne = per.id_personne;


-- --recuperer les temps de disponibilites pour l'entretien dans un département
-- CREATE OR REPLACE VIEW v_disponibilite_employe_valide as(
--     SELECT de.*,em.poste
--     FROM disponibilite_employe de  
--     JOIN (
--         SELECT * 
--         FROM employes 
--         where id_departement = 1
--     )em
--     ON de.id_employe = em.id_employe
--     and de.est_valide
-- );

-- CREATE OR REPLACE VIEW v_entretien_candidat_apres_une_date as(
-- SELECT  pe.*,e.id_departement
--     FROM candidats c
--     JOIN planning_entretien pe
--     ON pe.id_candidat = c.id_candidat
--     JOIN (
--         SELECT
--             poste,id_departement
--         FROM
--             employes 
--         WHERE id_departement = 1
--         )e
--     ON e.poste = c.poste
--     WHERE pe.date_heure_entretien >=""
-- );

-- CREATE OR REPLACE VIEW v_disponibilite_employe_valide as(
-- SELECT de.*,em.id_departement,em.poste,CASE jour
--     WHEN 'Lundi'THEN 1
--     WHEN 'Mardi'THEN 2
--     WHEN 'Mercredi'THEN 3
--     WHEN 'Jeudi'THEN 4
--     WHEN 'Vendredi'THEN 5
--     WHEN 'Samedi'THEN 6
--     WHEN 'Dimanche'THEN 7
--     END as numero_jour
--     FROM  disponibilite_entretien de 
--     JOIN (
--         SELECT 
--         id_employe,poste,id_departement
--         FROM employes
--     )em
--     ON em.id_employe = de.id_employe
--     and de.est_valide
-- );

--recuperer  le departement de chaque employe responsable
CREATE OR REPLACE VIEW v_responsable_avec_departement AS
    SELECT 
        re.id_responsable,
        re.id_employe,
        em_de.nom as nom_departement,
        em_de.id_departement
    FROM responsable_entretien re
    JOIN (
        SELECT EM.*,de.nom
        FROM (SELECT *
        FROM employes em
        )Em
        JOIN departements de
        ON de.id_departement = Em.id_departement
    )em_de
    ON em_de.id_employe = re.id_employe;

--recuperer le planning d'entretien le plus recent pour un responsable d'enetretien
CREATE OR REPLACE VIEW v_planning_entretien_recent_responsable as
SELECT *
FROM planning_entretien 
where date_heure_entretien in(
    SELECT MAX(date_heure_entretien)
    FROM  planning_entretien
    group by id_responsable
);

